version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: POqtSKRshJavfUCVuLCGsBKVrlRTACmV
      POSTGRES_HOST: roundhouse.proxy.rlwy.net
      POSTGRES_PORT: 57119
      POSTGRES_DB: railway
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    environment:
      - REDIS_USER = default
      - REDIS_PASSWORD = POqtSKRshJavfUCVuLCGsBKVrlRTACmV
      - REDIS_HOST = roundhouse.proxy.rlwy.net
      - REDIS_PORT = 57119
    env_file:
      - .env

  app:
    build:
      context: src
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 7330:8000
    depends_on:
      - db
      - redis
